<?php 

$lang = [
    "Arabic" => "ar",
    "Bengali (Bangla)" => "bn",
    "Bulgarian (Bulgaria)" => "bg",
    "Chinese" => "zh-CN",
    "Croatian" => "hr",
    "Czech" => "cs",
    "Danish (Denmark)" => "da",
    "Dutch" => "nl",
    "English" => "en",
    "Espanol" => "es",
    "Estonian" => "et",
    "French" => "fr",
    "Finnish (Finland)" => "fi",
    "German" => "de",
    "Greek" => "el",
    "Hindi" => "hi",
    "Hungarian" => "hu",
    "Italian" => "it",
    "Japanese" => "ja",
    "Latin" => "la",
    "Lithuanian" => "lt",
    "Korean" => "ko",
    "Marathi" => "mr",
    "Norwegian (Norway)" => "no",
    "Polish" => "pl",
    "Portuguese" => "pt",
    "Romanian (Romania)" => "ro",
    "Russian" => "ru",
    "Slovak (Slovakia)" => "sk",
    "Slovene (Slovenia)" => "sl",
    "Swedish (Sweden)" => "sv",
    "Tamil" => "ta",
    "Telugu" => "te",
    "Turkish" => "tr",
    "Urdu" => "ur",
    "Vietnamese" => "vi",
    "Malayalam (Singapore)" => "ml",
    "Filipino (Philippines)" => "fil",
    "Siemese (Thailand)" => "th",
    "Albanian (Albania)" => "sq",
    "Swahili" => "sw",
    "Afrikaans" => "af",
    "Zulu" => "zu",
    "Indonesian" => "in",
    "Javanese" => "jv",
    "Gujarati" => "gu",
    "Persian" => "fa",
    "Kannada" => "kn",
    "Oriya" => "or",
    "Panjabi" => "pa",
    "Maithili" => "mai",
    "Hausa" => "ha",
    "Bhojpuri" => "bho",
    "Azerbaijani" => "az",
    "Burmese" => "my",
    "Awadhi" => "awa",
    "Thai" => "tha",
    "Sindhi" => "sd",
    "Igbo" => "ig",
    "Yoruba" => "yo",
];


ksort($lang);

$LANG_VALUES = join(",", array_values($lang));